### ISSUE TITLE
module 'keras.layers' has no attribute 'Wrapper'

### ISSUE THREAD

**Issue by Nadni** [CyberZHG/keras-transformer#26]
When trying to import the library, I get the following error:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\keras_transformer\__init__.py", line 2, in <module>
    from .transformer import *
  File "C:\Program Files\Python37\lib\site-packages\keras_transformer\transformer.py", line 4, in <module>
    from keras_multi_head import MultiHeadAttention
  File "C:\Program Files\Python37\lib\site-packages\keras_multi_head\__init__.py", line 1, in <module>
    from .multi_head import MultiHead
  File "C:\Program Files\Python37\lib\site-packages\keras_multi_head\multi_head.py", line 6, in <module>
    class MultiHead(keras.layers.Wrapper):
AttributeError: module 'keras.layers' has no attribute 'Wrapper'
```
I am using keras 2.2.5 and tensorflow 2.1.0 on Windows10

**Comment by Nadni** [comment]
Solved by uninstalling tensorflow, keras, and this library, then performing a clean installation.
